import matplotlib.pyplot as plt


def show_params(Xref):
    """
    Plot the key features
    :param Xref:
    :return:
    """
    plt.figure()
    plt.subplot(3, 1, 1)
    plt.title("Volume")
    plt.plot(Xref.V.t, Xref.V.y)
    plt.xticks([])
    plt.subplot(3, 1, 2)
    plt.title("Penicillin Concentration")
    plt.plot(Xref.P.t, Xref.P.y)
    plt.xticks([])
    plt.subplot(3, 1, 3)
    plt.title("Discharge rate")
    plt.plot(Xref.Fremoved.t, Xref.Fremoved.y)
    plt.xticks([])

    plt.figure()
    plt.subplot(4, 4, 1)
    plt.title("Sugar feed rate")
    plt.plot(Xref.Fs.t, Xref.Fs.y)
    plt.xticks([])
    plt.subplot(4, 4, 2)
    plt.title("Soil bean feed rate")
    plt.plot(Xref.Foil.t, Xref.Foil.y)
    plt.xticks([])
    plt.subplot(4, 4, 3)
    plt.title("Aeration rate")
    plt.plot(Xref.Fg.t, Xref.Fg.y)
    plt.xticks([])
    plt.subplot(4, 4, 4)
    plt.title("Back pressure")
    plt.plot(Xref.pressure.t, Xref.pressure.y)
    plt.xticks([])
    plt.subplot(4, 4, 5)
    plt.title("Water injection/dilution")
    plt.plot(Xref.Fw.t, Xref.Fw.y)
    plt.xticks([])
    plt.subplot(4, 4, 6)
    plt.title("Phenylacetic acid flow rate")
    plt.plot(Xref.Fpaa.t, Xref.Fpaa.y, 'g')
    plt.xticks([])
    plt.subplot(4, 4, 7)
    plt.title("pH")
    plt.plot(Xref.pH.t, Xref.pH.y, 'r')
    plt.xticks([])
    plt.subplot(4, 4, 8)
    plt.title("Temperature")
    plt.plot(Xref.T.t, Xref.T.y, 'r')
    plt.xticks([])
    plt.subplot(4, 4, 9)
    plt.title("Acid flow rate")
    plt.plot(Xref.Fa.t, Xref.Fa.y)
    plt.xticks([])
    plt.subplot(4, 4, 10)
    plt.title("Base flow rate")
    plt.plot(Xref.Fb.t, Xref.Fb.y)
    plt.xticks([])
    plt.subplot(4, 4, 11)
    plt.title("Cooling water")
    plt.plot(Xref.Fc.t, Xref.Fc.y)
    plt.xticks([])
    plt.subplot(4, 4, 12)
    plt.title("Heating water")
    plt.plot(Xref.Fh.t, Xref.Fh.y)
    plt.xticks([])
    plt.subplot(4, 4, 13)
    plt.title("Raman Spectra")
    plt.plot(Xref.Raman_Spec.Wavenumber, Xref.Raman_Spec.Intensity.T)
    plt.xticks([])
    plt.subplot(4, 4, 14)
    plt.title("Vessel Weight")
    plt.plot(Xref.Wt.t, Xref.Wt.y)
    plt.xticks([])
    plt.subplot(4, 4, 15)
    plt.title("Dissolved oxygen concen.")
    plt.plot(Xref.DO2.t, Xref.DO2.y)
    plt.xticks([])
    plt.subplot(4, 4, 16)
    plt.title("Oxygen in percent in off-gas")
    plt.plot(Xref.O2.t, Xref.O2.y)
    plt.xticks([])

    plt.show()
